hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/DoubleLinkedList.o -c ./src/DoubleLinkedList.cpp
	g++ -I ./include/ -o ./bin/Program ./lib/DoubleLinkedList.o ./src/Test.cpp
	
calistir:
	./bin/Program